### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by dtKinger** [Knokd/docs.knokd.com#16]
- [x] Remove the `User-agent: * Disallow: /` from robots.txt
- [x] Write meta descriptions for every page
- [x] Fill out the sections export for H2s in each doc
- [x] (optional) Add a "Listing tags" section to Listing Types doc to explain `Coming Soon`, `Exclusive`, `Assignment` instead of just having 'restricted' and unrestricted buckets
- [x] Include the marketing toolkit content
    - [x] Create download buttons for assets 

Post launch:
- [x] Run a broken-link checker in production

cc:/ @andrewpaliga

**Comment by dtKinger** [comment]
- [ ] Recommended - Hook up the document feedback ("Was this page helpful? Yes / No") to Google analytics or track it in some way that's natural for your team. LMK If I can assist with that, though I may lack permissions to third-party accounts.
<img width="452" alt="Screenshot 2024-05-08 at 12 18 15 AM" src="https://github.com/Knokd/docs.knokd.com/assets/4868816/9c8650ad-14d4-4525-8861-36dbd17705a6">

**Comment by andrewpaliga** [comment]
Agree with all, I'd just leave the hooking up the "wast this helpful" thing out for now. We can add that in the future but honestly we won't be looking at this data anytime soon.
